//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LessMsi.Gui.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LessMsi.Gui.Resources.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shortcut Item to Explorer.
        /// </summary>
        internal static string AddShortcutText {
            get {
                return ResourceManager.GetString("AddShortcutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds &apos;Extract&apos; &amp; &apos;Explore&apos; menu items to the right-click context menu of .msi files.
        /// </summary>
        internal static string AddShortcutTextNote {
            get {
                return ResourceManager.GetString("AddShortcutTextNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path is badly formed.
        /// </summary>
        internal static string BadlyFormedFilePathError {
            get {
                return ResourceManager.GetString("BadlyFormedFilePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        internal static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path is empty.
        /// </summary>
        internal static string EmptyFilePathError {
            get {
                return ResourceManager.GetString("EmptyFilePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xtract.
        /// </summary>
        internal static string Extract {
            get {
                return ResourceManager.GetString("Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Files.
        /// </summary>
        internal static string ExtractFiles {
            get {
                return ResourceManager.GetString("ExtractFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Stream Files....
        /// </summary>
        internal static string ExtractStreamFiles {
            get {
                return ResourceManager.GetString("ExtractStreamFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; does not exist.
        /// </summary>
        internal static string FileExistError {
            get {
                return ResourceManager.GetString("FileExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string FileMenuLabel {
            get {
                return ResourceManager.GetString("FileMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files found..
        /// </summary>
        internal static string FilesFoundStatus {
            get {
                return ResourceManager.GetString("FilesFoundStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find stream for CAB &apos;{0}&apos;.
        /// </summary>
        internal static string FindStreamError {
            get {
                return ResourceManager.GetString("FindStreamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path contains invalid characters.
        /// </summary>
        internal static string InvalidCharsInFilePathError {
            get {
                return ResourceManager.GetString("InvalidCharsInFilePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading summary information.
        /// </summary>
        internal static string LoadingSummaryInfoError {
            get {
                return ResourceManager.GetString("LoadingSummaryInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading list of tables....
        /// </summary>
        internal static string LoadingTablesStatus {
            get {
                return ResourceManager.GetString("LoadingTablesStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing File.
        /// </summary>
        internal static string MissingFile {
            get {
                return ResourceManager.GetString("MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files present.
        /// </summary>
        internal static string NoFilesPresentStatus {
            get {
                return ResourceManager.GetString("NoFilesPresentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open file.
        /// </summary>
        internal static string OpenFileError {
            get {
                return ResourceManager.GetString("OpenFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Preferences.
        /// </summary>
        internal static string PreferencesMenuLabel {
            get {
                return ResourceManager.GetString("PreferencesMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing table &apos;{0}&apos;..
        /// </summary>
        internal static string ProcessingTableStatus {
            get {
                return ResourceManager.GetString("ProcessingTableStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        internal static string RecentFiles {
            get {
                return ResourceManager.GetString("RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Shortcut Item.
        /// </summary>
        internal static string RemoveShortcutText {
            get {
                return ResourceManager.GetString("RemoveShortcutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the context menu if it exists.
        /// </summary>
        internal static string RemoveShortcutTextNote {
            get {
                return ResourceManager.GetString("RemoveShortcutTextNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should be in the same directory as.
        /// </summary>
        internal static string SameDirMassage {
            get {
                return ResourceManager.GetString("SameDirMassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search File.
        /// </summary>
        internal static string SearchFile {
            get {
                return ResourceManager.GetString("SearchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select some or all of the files to extract them..
        /// </summary>
        internal static string SelectFilesMessage {
            get {
                return ResourceManager.GetString("SelectFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream.
        /// </summary>
        internal static string Stream {
            get {
                return ResourceManager.GetString("Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streams.
        /// </summary>
        internal static string Streams {
            get {
                return ResourceManager.GetString("Streams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Table.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table View.
        /// </summary>
        internal static string TableView {
            get {
                return ResourceManager.GetString("TableView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path is too long.
        /// </summary>
        internal static string TooLongFilePathError {
            get {
                return ResourceManager.GetString("TooLongFilePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Unselect All.
        /// </summary>
        internal static string UnselectAll {
            get {
                return ResourceManager.GetString("UnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot view files.
        /// </summary>
        internal static string ViewFilesError {
            get {
                return ResourceManager.GetString("ViewFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot view table.
        /// </summary>
        internal static string ViewTableError {
            get {
                return ResourceManager.GetString("ViewTableError", resourceCulture);
            }
        }
    }
}
