//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCopyright("Copyright Scott Willeke ©  2004-2013")]
[assembly: System.Reflection.AssemblyVersion("1.0.2")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.2")]


